### Register (crear usuario)
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nombreCompleto": "Elian",
  "email": "Elian@example.com",
  "password": "Secret123!"
}

### Login (obtén token)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "Elian@example.com",
  "password": "Secret123!"
}

### Get all users (protegido) 
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU1NjZkNTBhLTQyM2YtNDY4NC1iOGYzLTc0MmQxNmE4OGFjMiIsImVtYWlsIjoicHJ1ZWJhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYxNDA1NTY3LCJleHAiOjE3NjE0MDkxNjd9.fgZxnFCuMhW_J7_ouNbyxe5tInVPODownbgK0_FhNs0
Accept: application/json

### Get user by id (protegido)
GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkZTVjZWU2LWQwZDAtNGZkMi1iZjBmLTA2ZjMwNWM0NTlhMSIsImVtYWlsIjoicHJ1ZWJhMkBleGFtcGxlLmNvbSIsImlhdCI6MTc2MTQwOTA2MSwiZXhwIjoxNzYxNDEyNjYxfQ.JiTTCvmZShyEw-CtWvpcsKhcGSkjq1FJlRBu2SSgvUE
Accept: application/json

### Update user (PUT /users/:id)
PUT http://localhost:3000/users/4454b2ac-b71a-4603-b502-c9ecbd795e68
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ0NTRiMmFjLWI3MWEtNDYwMy1iNTAyLWM5ZWNiZDc5NWU2OCIsImVtYWlsIjoicHJ1ZWJhU1NTQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYxNDEwNjgzLCJleHAiOjE3NjE0MTQyODN9.RLAGbmrBHyixIqvorxguL9odjvyHDl4gh2IjmdOpFXs

{
  "nombreCompleto": "Nombre Actualizado",
  "email": "actualizado@example.com",
  "password": "NuevaPass123!",
  "role": "admin"
}

### Delete user (DELETE /users/:id)
DELETE http://localhost:3000/users/4454b2ac-b71a-4603-b502-c9ecbd795e68
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ0NTRiMmFjLWI3MWEtNDYwMy1iNTAyLWM5ZWNiZDc5NWU2OCIsImVtYWlsIjoicHJ1ZWJhU1NTQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYxNDEwNjgzLCJleHAiOjE3NjE0MTQyODN9.RLAGbmrBHyixIqvorxguL9odjvyHDl4gh2IjmdOpFXs
Accept: application/json

###
### Get all albums (public)
GET http://localhost:3000/albums
Accept: application/json

### Get album by idSlug (public)
GET http://localhost:3000/albums/2-the-raise-and-the-fall-of-a-midwest-princess
Accept: application/json


### get all albums (public)
GET http://localhost:3000/albums
Accept: application/json



### Create product (POST /albums)
POST http://localhost:3000/albums
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3NTM0YjBiLWFhNDEtNDlhZC1hODA1LTM1OGU0MjQ1MWRlMyIsImVtYWlsIjoiRWxpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjYwMjg5ODMsImV4cCI6MTc2NjAzMjU4M30.MWUNwUN2ynI2ewS-mVSrQd6vVACEeYJtdHHeGSwXPps

{
  "name": "Hit me hard and soft",
  "description": "busca encapsular extremos emocionales: la vulnerabilidad dulce y lo intenso/oscuro, reflejando la complejidad de las relaciones y la autoexploración, como una petición imposible de ser ambas cosas a la vez, fuerte y tierno",
  "price": 20.00,
  "categoryId":"3",
  "stock": 100,
  "author": "Billie Eilish",
  "discography": "Darkroom e Interscope Records",
  "deluxeVersion": true,
  "tags":[2, 8, 10, 11, 12]
  
}


### Create category (POST /category)
POST http://localhost:3000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3NTM0YjBiLWFhNDEtNDlhZC1hODA1LTM1OGU0MjQ1MWRlMyIsImVtYWlsIjoiRWxpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjYwMjg5ODMsImV4cCI6MTc2NjAzMjU4M30.MWUNwUN2ynI2ewS-mVSrQd6vVACEeYJtdHHeGSwXPps

{
  "name": "Pop Alternativo",
  "description": "género musical que fusiona la estructura pegadiza del pop con sonidos, instrumentación y temáticas del rock alternativo, el indie y géneros experimentales"
}

### create tags (POST /tags)
POST http://localhost:3000/tags
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3NTM0YjBiLWFhNDEtNDlhZC1hODA1LTM1OGU0MjQ1MWRlMyIsImVtYWlsIjoiRWxpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjYwMjk4MTksImV4cCI6MTc2NjAzMzQxOX0.t1N5kFiLBHERJEl3p82nhRTE16hU7lnWBCh64TL0XDw

{
  "name": "Pop Alternativo"
}

### Update album (PUT /albums/:id)
PUT http://localhost:3000/albums/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3NTM0YjBiLWFhNDEtNDlhZC1hODA1LTM1OGU0MjQ1MWRlMyIsImVtYWlsIjoiRWxpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3Njk1NDkzNTEsImV4cCI6MTc2OTU1Mjk1MX0.TwbNmhZqsxFigtD-FvPcD0y91Uu9S1x6CkPGKbDB0gw


{
  "name": "Evermore",
  "description": "Considerado el hermano del album 'folklore', evermore llega con una narrativa igual de profunda, contando historias complejas mediante retoricas y simbolismos.",
  "price": 12.99,
  "categoryId":"2",
  "stock": 100,
  "author": "Taylor Swift",
  "discography": "Republic Records.",
  "deluxeVersion": true,
  "tags":[6,7,8,9]
  
}

### update category (PUT /categories/:id)
DELETE http://localhost:3000/categories/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMxZWVkYjg1LTlhZjAtNGU3Ni05NDE1LTZjNzUzOGFlOTMwOCIsImVtYWlsIjoiRWxpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjUzOTkzNDYsImV4cCI6MTc2NTQwMjk0Nn0.vqO9lOaEHeM01IDUEhzyCPLXnCiQacOJ-LhyDHRKx1I

### Create order (POST /orders)
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3NTM0YjBiLWFhNDEtNDlhZC1hODA1LTM1OGU0MjQ1MWRlMyIsImVtYWlsIjoiRWxpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3Njk2MzMzNjUsImV4cCI6MTc2OTYzNjk2NX0.OQ8CYgY12rvFllPGIBNqnbxUsujiFgPDkmo4JFyPGZM

{
  "items": [
    { "id": 1, "quantity": 9 }
  ],
  "paymentMethod": "CreditCard",
  "paymentDetails": {
    "cardNumber": "4111111111111111", 
    "cvv": "123",
    "expMonth": "12",
    "expYear": "2030",
    "cardHolder": "APPROVED",
    "currency": "USD"
  }
}

### get all orders (GET /orders)
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3NTM0YjBiLWFhNDEtNDlhZC1hODA1LTM1OGU0MjQ1MWRlMyIsImVtYWlsIjoiRWxpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjYwMTk0NzEsImV4cCI6MTc2NjAyMzA3MX0.FIL-9Ivqfkzq9pkjJS2k4DD31Jy0ZFY5HEyFZw_GQ_E

### get order by id (GET /orders/:id)
GET http://localhost:3000/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3NTM0YjBiLWFhNDEtNDlhZC1hODA1LTM1OGU0MjQ1MWRlMyIsImVtYWlsIjoiRWxpYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjYwMTk0NzEsImV4cCI6MTc2NjAyMzA3MX0.FIL-9Ivqfkzq9pkjJS2k4DD31Jy0ZFY5HEyFZw_GQ_E